bookTiers:
  common:
    displayName: "&fCommon"
    xpCost: 1
    paneColor: 0
  uncommon:
    displayName: "&2Uncommon"
    xpCost: 2
    paneColor: 5
  epic:
    displayName: "&eEpic"
    xpCost: 3
    paneColor: 4
  godly:
    displayName: "&bGodly"
    xpCost: 3
    paneColor: 3
  dank:
    displayName: "&4D&3A&6N&cK&e"
    xpCost: 4
    paneColor: 6